# Generated by Django 3.2.3 on 2022-11-03 11:45

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(help_text='Class Id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('deadline', models.DateTimeField()),
                ('submission_capacity', models.IntegerField()),
                ('storage_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(help_text='Problem Id', primary_key=True, serialize=False)),
                ('explanation', models.CharField(max_length=2000)),
                ('reference', models.CharField(max_length=2000)),
                ('testcases', models.JSONField(default=dict)),
                ('skeleton_code', models.CharField(max_length=2000)),
                ('answer_code', models.CharField(max_length=2000)),
                ('related_content', models.CharField(max_length=2000)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='Problem_user_id', to='api.class')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(help_text='User Id', primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(help_text='Submission Id', primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField()),
                ('state', django_enumfield.db.fields.EnumField(default=0, enum=api.models.SubmissionState)),
                ('result', models.JSONField(default=dict)),
                ('analysis', models.JSONField(default=dict)),
                ('problem_id', models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, related_name='Submission_problem_id', to='api.problem')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='Submission_user_id', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(help_text='Storage Id', primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=2000)),
                ('updated_at', models.DateTimeField()),
                ('problem_id', models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, related_name='Storage_problem_id', to='api.problem')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='Storage_user_id', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(help_text='Enrollment Id', primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='Enrollment_class_id', to='api.class')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='Enrollment_user_id', to='api.user')),
            ],
        ),
    ]
