# Generated by Django 4.1.3 on 2022-11-17 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="order",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
