# Generated by Django 4.1.3 on 2022-11-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_groups_user_is_active_user_is_admin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
    ]
