# Generated by Django 4.1.3 on 2022-11-17 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_storage_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storage",
            name="order",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
