# Generated by Django 4.1.3 on 2022-11-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="student_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
