# Generated by Django 4.1.3 on 2022-11-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_storage_order"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="storage",
            unique_together={("user", "problem", "order")},
        ),
    ]
