# Generated by Django 4.1.3 on 2022-11-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_enrollment_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
