# Generated by Django 4.1.3 on 2022-11-27 23:57

import api.models.submission
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_submission_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="state",
            field=django_enumfield.db.fields.EnumField(
                default=1, enum=api.models.submission.SubmissionState
            ),
        ),
    ]
