# Generated by Django 4.1.3 on 2022-11-28 00:00

import api.models.submission
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_submission_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="state",
            field=django_enumfield.db.fields.EnumField(
                default=0, enum=api.models.submission.SubmissionState
            ),
        ),
    ]
